version: '3'
services:
  shitpost-api:
    image: ghcr.io/regulad/shitpost-api:latest
    ports:
      - 8081:8081/tcp
  mongo:
    image: mongo
    ports:
      27017:27017/tcp
    volumes:
      - db:/data/db
volumes:
  db:
