version: '3'
services:
  easy-gtts-api:
    image: docker.pkg.github.com/regulad/shitpost-api/shitpost-api:latest
    ports:
      - 8081:8081/tcp
    volumes:
      - config:/app/config
volumes:
  config:
